// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var Theme$ReactTemplate = require("./Theme.js");
var CommonStyles$ReactTemplate = require("./CommonStyles.js");
var GlobalStyles$ReactTemplate = require("./GlobalStyles.js");
var HydrateGlamor$ReactTemplate = require("./HydrateGlamor.js");

var sidebarWidth = TypedGlamor.pct(10);

var container = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.position(TypedGlamor.absolute),
      /* :: */[
        TypedGlamor.width(TypedGlamor.pct(100)),
        /* :: */[
          TypedGlamor.height(TypedGlamor.pct(100)),
          /* :: */[
            TypedGlamor.overflow(TypedGlamor.auto),
            /* :: */[
              TypedGlamor.display(TypedGlamor.flex),
              /* :: */[
                TypedGlamor.flexDirection(TypedGlamor.column),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var headerContainer = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.backgroundColor(TypedGlamor.white),
      /* :: */[
        TypedGlamor.borderBottom3(TypedGlamor.rem(0.1), TypedGlamor.solid, TypedGlamor.hex("ccc")),
        /* :: */[
          TypedGlamor.borderTop3(TypedGlamor.rem(0.2), TypedGlamor.solid, TypedGlamor.hex("ccc")),
          /* [] */0
        ]
      ]
    ]);

var header = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.widthContainer], /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.justifyContent(TypedGlamor.spaceBetween),
        /* :: */[
          TypedGlamor.alignItems(TypedGlamor.center),
          /* :: */[
            TypedGlamor.textAlign(TypedGlamor.center),
            /* :: */[
              TypedGlamor.height(TypedGlamor.rem(6)),
              /* :: */[
                TypedGlamor.fontWeight(TypedGlamor._700),
                /* :: */[
                  TypedGlamor.fontSize(TypedGlamor.rem(1.6)),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var main = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.widthContainer], /* :: */[
      TypedGlamor.flex3(1, 0, TypedGlamor.auto),
      /* [] */0
    ]);

var appLogoIcon = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.height(TypedGlamor.rem(3)),
      /* :: */[
        TypedGlamor.width(TypedGlamor.auto),
        /* :: */[
          TypedGlamor.unsafe("fill", "currentColor"),
          /* :: */[
            TypedGlamor.display(TypedGlamor.none),
            /* [] */0
          ]
        ]
      ]
    ]);

var appLogo = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.block),
      /* :: */[
        TypedGlamor.fontSize(TypedGlamor.rem(2.8)),
        /* :: */[
          TypedGlamor.fontWeight(TypedGlamor._700),
          /* [] */0
        ]
      ]
    ]);

var userNav = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.height(TypedGlamor.pct(100)),
        /* :: */[
          TypedGlamor.select("> *", /* :: */[
                TypedGlamor.border3(TypedGlamor.zero, TypedGlamor.solid, TypedGlamor.hex("ccc")),
                /* :: */[
                  TypedGlamor.borderRightWidth(TypedGlamor.rem(0.1)),
                  /* :: */[
                    TypedGlamor.display(TypedGlamor.flex),
                    /* :: */[
                      TypedGlamor.alignItems(TypedGlamor.center),
                      /* :: */[
                        TypedGlamor.padding2(TypedGlamor.zero, TypedGlamor.rem(1.5)),
                        /* :: */[
                          TypedGlamor.firstChild(/* :: */[
                                TypedGlamor.borderLeftWidth(TypedGlamor.rem(0.1)),
                                /* [] */0
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]),
          /* :: */[
            TypedGlamor.select("& a", /* :: */[
                  TypedGlamor.cursor(TypedGlamor.pointer),
                  /* :: */[
                    TypedGlamor.hover(/* :: */[
                          TypedGlamor.backgroundColor(TypedGlamor.hex("292d801a")),
                          /* :: */[
                            TypedGlamor.textDecoration(TypedGlamor.none),
                            /* [] */0
                          ]
                        ]),
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var userAvatar = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.border3(TypedGlamor.rem(0.1), TypedGlamor.solid, Theme$ReactTemplate.Color[/* link */6]),
      /* :: */[
        TypedGlamor.borderRadius(TypedGlamor.pct(50)),
        /* :: */[
          TypedGlamor.width(TypedGlamor.rem(3.5)),
          /* :: */[
            TypedGlamor.height(TypedGlamor.rem(3.5)),
            /* :: */[
              TypedGlamor.marginRight(TypedGlamor.rem(1)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var loginLink = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.button], /* [] */0);

var footerContainer = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.marginTop(TypedGlamor.rem(2)),
      /* :: */[
        TypedGlamor.backgroundColor(TypedGlamor.white),
        /* :: */[
          TypedGlamor.fontSize(TypedGlamor.rem(1.4)),
          /* :: */[
            TypedGlamor.padding(TypedGlamor.rem(2)),
            /* :: */[
              TypedGlamor.borderTop3(TypedGlamor.rem(0.1), TypedGlamor.solid, TypedGlamor.hex("ccc")),
              /* :: */[
                TypedGlamor.borderBottom3(TypedGlamor.rem(0.2), TypedGlamor.solid, TypedGlamor.hex("ccc")),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var footer = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.widthContainer], /* :: */[
      TypedGlamor.flexShrink(0),
      /* :: */[
        TypedGlamor.display(TypedGlamor.flex),
        /* :: */[
          TypedGlamor.fontSize(TypedGlamor.rem(1.2)),
          /* :: */[
            TypedGlamor.color(TypedGlamor.hex("525252")),
            /* :: */[
              TypedGlamor.select("& > *", /* :: */[
                    TypedGlamor.flex_(TypedGlamor.$$int(1)),
                    /* :: */[
                      TypedGlamor.flexShrink(0),
                      /* :: */[
                        TypedGlamor.padding2(TypedGlamor.rem(2), TypedGlamor.rem(3)),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                TypedGlamor.select("& li", /* :: */[
                      TypedGlamor.display(TypedGlamor.flex),
                      /* :: */[
                        TypedGlamor.justifyContent(TypedGlamor.spaceBetween),
                        /* :: */[
                          TypedGlamor.padding2(TypedGlamor.rem(0.25), TypedGlamor.zero),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* :: */[
                  TypedGlamor.select("& h3", /* :: */[
                        TypedGlamor.marginBottom(TypedGlamor.rem(1)),
                        /* :: */[
                          TypedGlamor.color(TypedGlamor.hex("444")),
                          /* :: */[
                            TypedGlamor.fontSize(TypedGlamor.rem(1.4)),
                            /* [] */0
                          ]
                        ]
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var donateSection = TypedGlamor.css(/* None */0, /* [] */0);

var donateForm = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.marginTop(TypedGlamor.rem(1.5)),
        /* [] */0
      ]
    ]);

var donateInput = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.borderTopLeftRadius(Theme$ReactTemplate.borderRadius),
      /* :: */[
        TypedGlamor.borderBottomLeftRadius(Theme$ReactTemplate.borderRadius),
        /* :: */[
          TypedGlamor.padding2(TypedGlamor.zero, TypedGlamor.rem(0.5)),
          /* :: */[
            TypedGlamor.fontSize(TypedGlamor.rem(1.2)),
            /* :: */[
              TypedGlamor.border3(TypedGlamor.rem(0.1), TypedGlamor.solid, TypedGlamor.hex("ccc")),
              /* :: */[
                TypedGlamor.borderRightWidth(TypedGlamor.zero),
                /* :: */[
                  TypedGlamor.width(TypedGlamor.rem(10)),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var donateButton = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.button], /* :: */[
      TypedGlamor.borderTopLeftRadius(TypedGlamor.zero),
      /* :: */[
        TypedGlamor.borderBottomLeftRadius(TypedGlamor.zero),
        /* :: */[
          TypedGlamor.fontSize(TypedGlamor.rem(1.2)),
          /* :: */[
            TypedGlamor.padding2(TypedGlamor.rem(0.5), TypedGlamor.rem(0.5)),
            /* [] */0
          ]
        ]
      ]
    ]);

var donators = TypedGlamor.css(/* None */0, /* [] */0);

var _global = GlobalStyles$ReactTemplate._global;

exports._global = _global;
exports.sidebarWidth = sidebarWidth;
exports.container = container;
exports.headerContainer = headerContainer;
exports.header = header;
exports.main = main;
exports.appLogoIcon = appLogoIcon;
exports.appLogo = appLogo;
exports.userNav = userNav;
exports.userAvatar = userAvatar;
exports.loginLink = loginLink;
exports.footerContainer = footerContainer;
exports.footer = footer;
exports.donateSection = donateSection;
exports.donateForm = donateForm;
exports.donateInput = donateInput;
exports.donateButton = donateButton;
exports.donators = donators;
/* sidebarWidth Not a pure module */
