// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var Theme$ReactTemplate = require("./Theme.js");

TypedGlamor.$$global("*", /* :: */[
      TypedGlamor.unsafe("boxSizing", "border-box"),
      /* :: */[
        TypedGlamor.margin(TypedGlamor.zero),
        /* :: */[
          TypedGlamor.padding(TypedGlamor.zero),
          /* [] */0
        ]
      ]
    ]);

TypedGlamor.$$global("html", /* :: */[
      TypedGlamor.fontSize(TypedGlamor.px(10)),
      /* [] */0
    ]);

TypedGlamor.$$global("body", /* :: */[
      TypedGlamor.backgroundColor(Theme$ReactTemplate.Color[/* background */3]),
      /* :: */[
        TypedGlamor.color(Theme$ReactTemplate.Color[/* text */5]),
        /* :: */[
          TypedGlamor.fontFamilies(/* :: */[
                "aktiv-grotesk",
                /* :: */[
                  "-apple-system",
                  /* :: */[
                    "BlinkMacSystemFont",
                    /* :: */[
                      "Segoe UI",
                      /* :: */[
                        "Roboto",
                        /* :: */[
                          "Oxygen",
                          /* :: */[
                            "Ubuntu",
                            /* :: */[
                              "Cantarell",
                              /* :: */[
                                "Fira Sans",
                                /* :: */[
                                  "Droid Sans",
                                  /* :: */[
                                    "Helvetica Neue",
                                    /* :: */[
                                      "sans-serif",
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

TypedGlamor.$$global("*:focus", /* :: */[
      TypedGlamor.outlineStyle(TypedGlamor.none),
      /* [] */0
    ]);

TypedGlamor.$$global("a", /* :: */[
      TypedGlamor.color(Theme$ReactTemplate.Color[/* link */6]),
      /* :: */[
        TypedGlamor.textDecoration(TypedGlamor.none),
        /* [] */0
      ]
    ]);

TypedGlamor.$$global("a:hover", /* :: */[
      TypedGlamor.textDecoration(TypedGlamor.underline),
      /* [] */0
    ]);

TypedGlamor.$$global("svg", /* :: */[
      TypedGlamor.unsafe("fill", "currentColor"),
      /* [] */0
    ]);

var _global = TypedGlamor.$$global("[id^=__lpform_input]", /* :: */[
      TypedGlamor.display(TypedGlamor.none),
      /* [] */0
    ]);

exports._global = _global;
/*  Not a pure module */
