// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var HydrateGlamor$ReactTemplate = require("./HydrateGlamor.js");


/* HydrateGlamor-ReactTemplate Not a pure module */
