// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var Theme$ReactTemplate = require("./Theme.js");
var CommonStyles$ReactTemplate = require("./CommonStyles.js");
var HydrateGlamor$ReactTemplate = require("./HydrateGlamor.js");

var container = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.pagePrimaryBox], /* [] */0);

var fields = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.maxWidth(TypedGlamor.pct(75)),
      /* :: */[
        TypedGlamor.margin2(TypedGlamor.zero, TypedGlamor.auto),
        /* :: */[
          TypedGlamor.select("& input", /* :: */[
                TypedGlamor.display(TypedGlamor.block),
                /* :: */[
                  TypedGlamor.select("&:focus", /* :: */[
                        TypedGlamor.borderColor(Theme$ReactTemplate.Color[/* primary */0]),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

var field = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.position(TypedGlamor.relative),
      /* [] */0
    ]);

var invalid = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.backgroundColor(TypedGlamor.red),
      /* :: */[
        TypedGlamor.color(TypedGlamor.white),
        /* :: */[
          TypedGlamor.position(TypedGlamor.absolute),
          /* :: */[
            TypedGlamor.display(TypedGlamor.none),
            /* [] */0
          ]
        ]
      ]
    ]);

var valid = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.none),
      /* [] */0
    ]);

var label = TypedGlamor.css(/* None */0, /* [] */0);

var input = TypedGlamor.css(/* None */0, /* [] */0);

var errors = TypedGlamor.css(/* None */0, /* [] */0);

var titleField = TypedGlamor.css(/* None */0, /* [] */0);

function titleInput(isValid) {
  return TypedGlamor.css(/* None */0, /* :: */[
              TypedGlamor.width(TypedGlamor.pct(100)),
              /* :: */[
                TypedGlamor.fontSize(TypedGlamor.rem(2.4)),
                /* :: */[
                  TypedGlamor.fontWeight(TypedGlamor._700),
                  /* :: */[
                    TypedGlamor.marginBottom(TypedGlamor.rem(1)),
                    /* :: */[
                      TypedGlamor.borderStyle(TypedGlamor.solid),
                      /* :: */[
                        TypedGlamor.borderWidth(TypedGlamor.rem(0.3)),
                        /* :: */[
                          TypedGlamor.borderColor(isValid ? TypedGlamor.hex("ccc") : TypedGlamor.hex("d60000")),
                          /* :: */[
                            TypedGlamor.borderRadius(Theme$ReactTemplate.borderRadius),
                            /* :: */[
                              TypedGlamor.padding2(TypedGlamor.rem(1.5), TypedGlamor.rem(2)),
                              /* :: */[
                                TypedGlamor.unsafe("backgroundImage", "none !important"),
                                /* :: */[
                                  TypedGlamor.select("&::placeholder", /* :: */[
                                        TypedGlamor.color(isValid ? TypedGlamor.hex("ccc") : TypedGlamor.hex("d60000")),
                                        /* [] */0
                                      ]),
                                  /* :: */[
                                    TypedGlamor.select("&:focus", /* :: */[
                                          TypedGlamor.select("&::placeholder", /* :: */[
                                                TypedGlamor.color(TypedGlamor.hex("ccc")),
                                                /* [] */0
                                              ]),
                                          /* [] */0
                                        ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function optionField(isValid) {
  return TypedGlamor.css(/* None */0, /* :: */[
              TypedGlamor.display(TypedGlamor.flex),
              /* :: */[
                TypedGlamor.fontSize(TypedGlamor.rem(1.6)),
                /* :: */[
                  TypedGlamor.height(TypedGlamor.rem(4)),
                  /* :: */[
                    TypedGlamor.alignItems(TypedGlamor.center),
                    /* :: */[
                      TypedGlamor.marginBottom(TypedGlamor.rem(1)),
                      /* :: */[
                        TypedGlamor.color(TypedGlamor.hex(isValid ? "333" : "d60000")),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var optionNum = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.fontWeight(TypedGlamor.bold),
      /* :: */[
        TypedGlamor.width(TypedGlamor.rem(2)),
        /* :: */[
          TypedGlamor.textAlign(TypedGlamor.center),
          /* :: */[
            TypedGlamor.lineHeight(TypedGlamor.rem(3)),
            /* :: */[
              TypedGlamor.borderRadius(TypedGlamor.pct(50)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

function optionInput(isValid) {
  return TypedGlamor.css(/* None */0, /* :: */[
              TypedGlamor.width(TypedGlamor.pct(100)),
              /* :: */[
                TypedGlamor.height(TypedGlamor.pct(100)),
                /* :: */[
                  TypedGlamor.flex_(TypedGlamor.$$int(1)),
                  /* :: */[
                    TypedGlamor.margin2(TypedGlamor.zero, TypedGlamor.rem(1)),
                    /* :: */[
                      TypedGlamor.fontSize(TypedGlamor.rem(1.6)),
                      /* :: */[
                        TypedGlamor.borderStyle(TypedGlamor.solid),
                        /* :: */[
                          TypedGlamor.borderColor(isValid ? TypedGlamor.hex("ccc") : TypedGlamor.hex("d60000")),
                          /* :: */[
                            TypedGlamor.borderWidth(TypedGlamor.zero),
                            /* :: */[
                              TypedGlamor.borderBottomWidth(TypedGlamor.rem(0.3)),
                              /* :: */[
                                TypedGlamor.select("&::placeholder", /* :: */[
                                      TypedGlamor.color(isValid ? TypedGlamor.hex("ccc") : TypedGlamor.hex("d60000")),
                                      /* [] */0
                                    ]),
                                /* :: */[
                                  TypedGlamor.select("&:focus", /* :: */[
                                        TypedGlamor.select("&::placeholder", /* :: */[
                                              TypedGlamor.color(TypedGlamor.hex("ccc")),
                                              /* [] */0
                                            ]),
                                        /* [] */0
                                      ]),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var optionRemove = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.fontWeight(TypedGlamor.bold),
      /* :: */[
        TypedGlamor.textAlign(TypedGlamor.center),
        /* :: */[
          TypedGlamor.cursor(TypedGlamor.pointer),
          /* :: */[
            TypedGlamor.color(Theme$ReactTemplate.Color[/* primary */0]),
            /* :: */[
              TypedGlamor.select("& svg", /* :: */[
                    TypedGlamor.display(TypedGlamor.block),
                    /* :: */[
                      TypedGlamor.margin2(TypedGlamor.zero, TypedGlamor.auto),
                      /* [] */0
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var submitButton = TypedGlamor.css(/* Some */[CommonStyles$ReactTemplate.button], /* :: */[
      TypedGlamor.margin3(TypedGlamor.rem(2.5), TypedGlamor.auto, TypedGlamor.zero),
      /* :: */[
        TypedGlamor.display(TypedGlamor.block),
        /* :: */[
          TypedGlamor.fontSize(TypedGlamor.rem(2.4)),
          /* :: */[
            TypedGlamor.fontWeight(TypedGlamor._700),
            /* :: */[
              TypedGlamor.padding2(TypedGlamor.rem(1), TypedGlamor.rem(2)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var advancedFields = TypedGlamor.css(/* None */0, /* [] */0);

exports.container = container;
exports.fields = fields;
exports.field = field;
exports.invalid = invalid;
exports.valid = valid;
exports.label = label;
exports.input = input;
exports.errors = errors;
exports.titleField = titleField;
exports.titleInput = titleInput;
exports.optionField = optionField;
exports.optionNum = optionNum;
exports.optionInput = optionInput;
exports.optionRemove = optionRemove;
exports.submitButton = submitButton;
exports.advancedFields = advancedFields;
/* container Not a pure module */
