// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var Link$ReactTemplate = require("./Link.js");
var Route$ReactTemplate = require("../Route.js");
var Words$ReactTemplate = require("../Words.js");
var HomePage$ReactTemplate = require("./HomePage.js");
var AboutPage$ReactTemplate = require("./AboutPage.js");
var AppStyles$ReactTemplate = require("../Styles/AppStyles.js");
var StatsPage$ReactTemplate = require("./StatsPage.js");
var MarketPage$ReactTemplate = require("./MarketPage.js");
var TreasuryPage$ReactTemplate = require("./TreasuryPage.js");
var GovernancePage$ReactTemplate = require("./GovernancePage.js");

var component = ReasonReact.statelessComponent("AppLink");

function make(current, route, label, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var isSelected = current === route;
              var className = TypedGlamor.toString(AppStyles$ReactTemplate.appLink(isSelected));
              return ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(route, /* Some */[className], /* array */[Words$ReactTemplate.translate(/* English */0, label)]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var AppLink = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("PrimaryNav");

function make$1(current, _) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: TypedGlamor.toString(AppStyles$ReactTemplate.primaryNav)
                        }, ReasonReact.element(/* None */0, /* None */0, make(current, /* Market */1, /* Market */0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(current, /* Governance */3, /* Games */1, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(current, /* Governance */3, /* Governance */3, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(current, /* Stats */4, /* Upload */6, /* array */[])));
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* subscriptions */component$1[/* subscriptions */13],
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

var PrimaryNav = /* module */[
  /* component */component$1,
  /* make */make$1
];

var component$2 = ReasonReact.statelessComponent("SecondaryNav");

function make$2(current, _) {
  return /* record */[
          /* debugName */component$2[/* debugName */0],
          /* reactClassInternal */component$2[/* reactClassInternal */1],
          /* handedOffState */component$2[/* handedOffState */2],
          /* willReceiveProps */component$2[/* willReceiveProps */3],
          /* didMount */component$2[/* didMount */4],
          /* didUpdate */component$2[/* didUpdate */5],
          /* willUnmount */component$2[/* willUnmount */6],
          /* willUpdate */component$2[/* willUpdate */7],
          /* shouldUpdate */component$2[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: TypedGlamor.toString(AppStyles$ReactTemplate.secondaryNav)
                        }, ReasonReact.element(/* None */0, /* None */0, make(current, /* Stats */4, /* Stats */4, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(current, /* About */5, /* About */7, /* array */[])));
            }),
          /* initialState */component$2[/* initialState */10],
          /* retainedProps */component$2[/* retainedProps */11],
          /* reducer */component$2[/* reducer */12],
          /* subscriptions */component$2[/* subscriptions */13],
          /* jsElementWrapped */component$2[/* jsElementWrapped */14]
        ];
}

var SecondaryNav = /* module */[
  /* component */component$2,
  /* make */make$2
];

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

var component$3 = ReasonReact.reducerComponent("App");

function make$3() {
  return /* record */[
          /* debugName */component$3[/* debugName */0],
          /* reactClassInternal */component$3[/* reactClassInternal */1],
          /* handedOffState */component$3[/* handedOffState */2],
          /* willReceiveProps */component$3[/* willReceiveProps */3],
          /* didMount */(function () {
              document.addEventListener("scatterLoaded", (function () {
                      console.log("scatter loaded");
                      return /* () */0;
                    }));
              return /* () */0;
            }),
          /* didUpdate */component$3[/* didUpdate */5],
          /* willUnmount */component$3[/* willUnmount */6],
          /* willUpdate */component$3[/* willUpdate */7],
          /* shouldUpdate */component$3[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var tmp;
              switch (match) {
                case 0 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, HomePage$ReactTemplate.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, MarketPage$ReactTemplate.make(/* array */[]));
                    break;
                case 2 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, TreasuryPage$ReactTemplate.make(/* array */[]));
                    break;
                case 3 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, GovernancePage$ReactTemplate.make(/* array */[]));
                    break;
                case 4 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, StatsPage$ReactTemplate.make(/* array */[]));
                    break;
                case 5 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, AboutPage$ReactTemplate.make(/* array */[]));
                    break;
                
              }
              return React.createElement("div", {
                          className: TypedGlamor.toString(AppStyles$ReactTemplate.box)
                        }, React.createElement("header", {
                              className: TypedGlamor.toString(AppStyles$ReactTemplate.header)
                            }, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(/* Home */0, /* Some */[TypedGlamor.toString(AppStyles$ReactTemplate.appLogo)], /* array */["TGFP"])), ReasonReact.element(/* None */0, /* None */0, make$1(self[/* state */1][/* route */0], /* array */[])), ReasonReact.element(/* None */0, /* None */0, make$2(self[/* state */1][/* route */0], /* array */[])), React.createElement("nav", {
                                  className: TypedGlamor.toString(AppStyles$ReactTemplate.userNav)
                                }, React.createElement("a", {
                                      className: TypedGlamor.toString(AppStyles$ReactTemplate.loginLink),
                                      href: "#"
                                    }, "Login"))), tmp);
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component$3[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[Route$ReactTemplate.fromUrl(url)]);
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component$3[/* jsElementWrapped */14]
        ];
}

var Styles = 0;

exports.Styles = Styles;
exports.AppLink = AppLink;
exports.PrimaryNav = PrimaryNav;
exports.SecondaryNav = SecondaryNav;
exports.reducer = reducer;
exports.component = component$3;
exports.make = make$3;
/* component Not a pure module */
