// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var Api$ReactTemplate = require("../Api.js");
var Env$ReactTemplate = require("../Env.js");
var Link$ReactTemplate = require("./Link.js");
var Route$ReactTemplate = require("../Route.js");
var Context$ReactTemplate = require("../Context.js");
var Scatter$ReactTemplate = require("../External/Scatter.js");
var HomePage$ReactTemplate = require("../Pages/HomePage.js");
var PollPage$ReactTemplate = require("../Pages/PollPage.js");
var AboutPage$ReactTemplate = require("../Pages/AboutPage.js");
var AppStyles$ReactTemplate = require("../Styles/AppStyles.js");
var ProfilePage$ReactTemplate = require("../Pages/ProfilePage.js");
var PollResultsPage$ReactTemplate = require("../Pages/PollResultsPage.js");

var temp = ( window.Eos = require('eosjs') );

function reducer(action, state) {
  switch (action.tag | 0) {
    case 0 : 
        return /* Update */Block.__(0, [/* record */[
                    /* context */state[/* context */0],
                    /* route */action[0]
                  ]]);
    case 1 : 
        var init = state[/* context */0];
        return /* Update */Block.__(0, [/* record */[
                    /* context : record */[
                      /* scatter */init[/* scatter */0],
                      /* identity */action[0],
                      /* language */init[/* language */2]
                    ],
                    /* route */state[/* route */1]
                  ]]);
    case 2 : 
        var scatter = action[0];
        var init$1 = state[/* context */0];
        return /* Update */Block.__(0, [/* record */[
                    /* context : record */[
                      /* scatter : Some */[scatter],
                      /* identity */Scatter$ReactTemplate.identity(scatter),
                      /* language */init$1[/* language */2]
                    ],
                    /* route */state[/* route */1]
                  ]]);
    
  }
}

var component = ReasonReact.reducerComponent("App");

function clickedLogin(self, scatter, _) {
  Scatter$ReactTemplate.getIdentity(scatter, /* Some */[/* array */[Env$ReactTemplate.network]], /* None */0, /* None */0, /* () */0).then((function (identity) {
          console.log(identity);
          Curry._1(self[/* send */3], /* ChangeIdentity */Block.__(1, [/* Some */[identity]]));
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function clickedLogout(self, scatter, _) {
  Scatter$ReactTemplate.forgetIdentity(scatter).then((function () {
          Curry._1(self[/* send */3], /* ChangeIdentity */Block.__(1, [/* None */0]));
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Scatter$ReactTemplate.onLoad((function () {
                            var match = window.scatter;
                            if (match == null) {
                              return /* () */0;
                            } else {
                              Curry._1(self[/* send */3], /* ScatterLoaded */Block.__(2, [match]));
                              Api$ReactTemplate.Contract[/* make */0](match).then((function () {
                                        return Promise.resolve(/* () */0);
                                      })).then((function (result) {
                                      console.log("Created", result);
                                      return Promise.resolve(/* () */0);
                                    }));
                              return /* () */0;
                            }
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var context = self[/* state */1][/* context */0];
              var match = context[/* scatter */0];
              var tmp;
              if (match) {
                var scatter = match[0];
                var match$1 = context[/* identity */1];
                if (match$1) {
                  var name = Caml_array.caml_array_get(match$1[0].accounts, 0).name;
                  tmp = React.createElement("nav", {
                        className: TypedGlamor.toString(AppStyles$ReactTemplate.userNav)
                      }, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(/* Profile */Block.__(0, [name]), /* None */0, /* array */[name])), React.createElement("button", {
                            onClick: (function (param) {
                                return clickedLogout(self, scatter, param);
                              })
                          }, "Logout"));
                } else {
                  tmp = React.createElement("button", {
                        className: TypedGlamor.toString(AppStyles$ReactTemplate.loginLink),
                        onClick: (function (param) {
                            return clickedLogin(self, scatter, param);
                          })
                      }, "Login");
                }
              } else {
                tmp = React.createElement("a", {
                      href: "https://get-scatter.com/"
                    }, "Get Scatter");
              }
              var match$2 = self[/* state */1][/* route */1];
              var tmp$1;
              if (typeof match$2 === "number") {
                tmp$1 = match$2 === 0 ? ReasonReact.element(/* None */0, /* None */0, HomePage$ReactTemplate.make(context, /* array */[])) : ReasonReact.element(/* None */0, /* None */0, AboutPage$ReactTemplate.make(/* array */[]));
              } else {
                switch (match$2.tag | 0) {
                  case 0 : 
                      tmp$1 = ReasonReact.element(/* None */0, /* None */0, ProfilePage$ReactTemplate.make(context, match$2[0], /* array */[]));
                      break;
                  case 1 : 
                      tmp$1 = ReasonReact.element(/* None */0, /* None */0, PollPage$ReactTemplate.make(context, match$2[0], match$2[1], /* array */[]));
                      break;
                  case 2 : 
                      tmp$1 = ReasonReact.element(/* None */0, /* None */0, PollResultsPage$ReactTemplate.make(context, match$2[0], match$2[1], /* array */[]));
                      break;
                  
                }
              }
              return React.createElement("div", {
                          className: TypedGlamor.toString(AppStyles$ReactTemplate.container)
                        }, React.createElement("header", {
                              className: TypedGlamor.toString(AppStyles$ReactTemplate.header)
                            }, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(/* Home */0, /* Some */[TypedGlamor.toString(AppStyles$ReactTemplate.appLogo)], /* array */["EOS Straw Poll"])), tmp), React.createElement("main", {
                              className: TypedGlamor.toString(AppStyles$ReactTemplate.main)
                            }, tmp$1), React.createElement("footer", {
                              className: TypedGlamor.toString(AppStyles$ReactTemplate.footer)
                            }, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(/* About */1, /* None */0, /* array */["About"]))));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* context */Context$ReactTemplate.empty,
                      /* route : Home */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */Block.__(0, [Route$ReactTemplate.fromUrl(url)]));
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Styles = 0;

exports.Styles = Styles;
exports.temp = temp;
exports.reducer = reducer;
exports.component = component;
exports.clickedLogin = clickedLogin;
exports.clickedLogout = clickedLogout;
exports.make = make;
/* temp Not a pure module */
