// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Formality__Form = require("re-formality/src/Formality__Form.bs.js");
var Forms$ReactTemplate = require("../Forms.js");
var Formality__Validation = require("re-formality/src/Formality__Validation.bs.js");
var Formality__PublicHelpers = require("re-formality/src/Formality__PublicHelpers.bs.js");

function get(field, state) {
  if (typeof field === "number") {
    switch (field) {
      case 0 : 
          return /* String */Block.__(0, [state[/* pollId */0]]);
      case 1 : 
          return /* String */Block.__(0, [state[/* title */1]]);
      case 2 : 
          return /* String */Block.__(0, [state[/* description */2]]);
      case 5 : 
          return /* String */Block.__(0, [state[/* whitelist */4]]);
      case 6 : 
          return /* String */Block.__(0, [state[/* blacklist */5]]);
      case 7 : 
          return /* Int */Block.__(1, [state[/* minChoices */6]]);
      case 8 : 
          return /* Int */Block.__(1, [state[/* maxChoices */7]]);
      case 9 : 
          return /* String */Block.__(0, [state[/* openTime */8]]);
      case 10 : 
          return /* String */Block.__(0, [state[/* closeTime */9]]);
      default:
        return /* NoValue */0;
    }
  } else if (field.tag) {
    return /* NoValue */0;
  } else {
    return /* String */Block.__(0, [Belt_Option.getWithDefault(Belt_Array.get(state[/* options */3], field[0]), "")]);
  }
}

function update(param, state) {
  var value = param[1];
  var field = param[0];
  if (typeof field === "number") {
    switch (field) {
      case 0 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */value[0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 1 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */value[0],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 2 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */value[0],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 3 : 
          state[/* options */3].push("");
          return state;
      case 4 : 
          return state;
      case 5 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */value[0],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 6 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */value[0],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 7 : 
          if (typeof value === "number" || !value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */value[0],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 8 : 
          if (typeof value === "number" || !value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */value[0],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 9 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */value[0],
                    /* closeTime */state[/* closeTime */9]
                  ];
          }
      case 10 : 
          if (typeof value === "number" || value.tag) {
            return Pervasives.failwith("Config.update function received bad input");
          } else {
            return /* record */[
                    /* pollId */state[/* pollId */0],
                    /* title */state[/* title */1],
                    /* description */state[/* description */2],
                    /* options */state[/* options */3],
                    /* whitelist */state[/* whitelist */4],
                    /* blacklist */state[/* blacklist */5],
                    /* minChoices */state[/* minChoices */6],
                    /* maxChoices */state[/* maxChoices */7],
                    /* openTime */state[/* openTime */8],
                    /* closeTime */value[0]
                  ];
          }
      
    }
  } else if (field.tag) {
    var index = field[0];
    return /* record */[
            /* pollId */state[/* pollId */0],
            /* title */state[/* title */1],
            /* description */state[/* description */2],
            /* options */state[/* options */3].filter((function (_, i) {
                    return i !== index;
                  })),
            /* whitelist */state[/* whitelist */4],
            /* blacklist */state[/* blacklist */5],
            /* minChoices */state[/* minChoices */6],
            /* maxChoices */state[/* maxChoices */7],
            /* openTime */state[/* openTime */8],
            /* closeTime */state[/* closeTime */9]
          ];
  } else if (typeof value === "number" || value.tag) {
    return Pervasives.failwith("Config.update function received bad input");
  } else {
    Belt_Array.set(state[/* options */3], field[0], value[0]);
    return state;
  }
}

var Validators = Formality__Validation.MakeValidators(/* module */[]);

var baseValidators = Curry._3(Validators[/* add */3], /* MinChoices */7, /* record */[
      /* strategy : OnFirstChange */1,
      /* dependents : None */0,
      /* validate */(function (value, _) {
          if (typeof value === "number") {
            return /* Invalid */["min choices must be 1 (testing)"];
          } else if (value.tag) {
            if (value[0] !== 1) {
              return /* Invalid */["min choices must be 1 (testing)"];
            } else {
              return /* Valid */0;
            }
          } else {
            return /* Invalid */["min choices must be 1 (testing)"];
          }
        })
    ], Curry._3(Validators[/* add */3], /* Description */2, /* record */[
          /* strategy : OnFirstChange */1,
          /* dependents : None */0,
          /* validate */(function (param, param$1) {
              return Forms$ReactTemplate.atMost(10, param, param$1);
            })
        ], Curry._3(Validators[/* add */3], /* Title */1, /* record */[
              /* strategy : OnFirstChange */1,
              /* dependents : None */0,
              /* validate */Forms$ReactTemplate.isRequired
            ], Curry._3(Validators[/* add */3], /* PollId */0, /* record */[
                  /* strategy : OnFirstChange */1,
                  /* dependents : None */0,
                  /* validate */(function (param, param$1) {
                      return Forms$ReactTemplate.thenValidate(Forms$ReactTemplate.isName, Forms$ReactTemplate.isRequired, param, param$1);
                    })
                ], Validators[/* empty */0]))));

var validators = Belt_Array.reduce(Belt_Array.range(0, 100), baseValidators, (function (result, i) {
        return Curry._3(Validators[/* add */3], /* Option */Block.__(0, [i]), /* record */[
                    /* strategy : OnFirstChange */1,
                    /* dependents : None */0,
                    /* validate */Forms$ReactTemplate.isBetween(1, 10)
                  ], result);
      }));

var Form = /* module */[
  /* valueEmpty */Forms$ReactTemplate.valueEmpty,
  /* thenValidate */Forms$ReactTemplate.thenValidate,
  /* isRequired */Forms$ReactTemplate.isRequired,
  /* nameRegex */Forms$ReactTemplate.nameRegex,
  /* isName */Forms$ReactTemplate.isName,
  /* stringLength */Forms$ReactTemplate.stringLength,
  /* atLeast */Forms$ReactTemplate.atLeast,
  /* atMost */Forms$ReactTemplate.atMost,
  /* isBetween */Forms$ReactTemplate.isBetween,
  /* get */get,
  /* update */update,
  /* Validators */Validators,
  /* baseValidators */baseValidators,
  /* validators */validators
];

var Container = Formality__Form.Make([
      get,
      update,
      Forms$ReactTemplate.valueEmpty,
      validators,
      [
        Validators[21],
        Validators[10]
      ]
    ]);

var component = ReasonReact.statelessComponent("PollForm-ReactTemplate");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Curry._3(Container[/* make */8], /* record */[
                              /* pollId */"",
                              /* title */"",
                              /* description */"",
                              /* options : array */[
                                "",
                                ""
                              ],
                              /* whitelist */"",
                              /* blacklist */"",
                              /* minChoices */1,
                              /* maxChoices */1,
                              /* openTime */"",
                              /* closeTime */""
                            ], (function (state, form) {
                                console.log("Called with:", state);
                                setTimeout((function () {
                                        Curry._1(form[/* notifyOnSuccess */0], /* None */0);
                                        setTimeout(form[/* reset */2], 3000);
                                        return /* () */0;
                                      }), 500);
                                return /* () */0;
                              }), (function (form) {
                                var partial_arg = form[/* submit */6];
                                var partial_arg$1 = Formality__PublicHelpers.Dom[/* preventDefault */6];
                                var match = Curry._1(form[/* results */2], /* PollId */0);
                                var tmp;
                                if (match) {
                                  var match$1 = match[0];
                                  tmp = match$1 ? React.createElement("div", {
                                          className: "failure"
                                        }, match$1[0]) : React.createElement("div", {
                                          className: "success"
                                        }, "✓");
                                } else {
                                  tmp = null;
                                }
                                var match$2 = Curry._1(form[/* results */2], /* Title */1);
                                var tmp$1;
                                if (match$2) {
                                  var match$3 = match$2[0];
                                  tmp$1 = match$3 ? React.createElement("div", {
                                          className: "failure"
                                        }, match$3[0]) : React.createElement("div", {
                                          className: "success"
                                        }, "✓");
                                } else {
                                  tmp$1 = null;
                                }
                                var match$4 = Curry._1(form[/* results */2], /* Description */2);
                                var tmp$2;
                                if (match$4) {
                                  var match$5 = match$4[0];
                                  tmp$2 = match$5 ? React.createElement("div", {
                                          className: "failure"
                                        }, match$5[0]) : React.createElement("div", {
                                          className: "success"
                                        }, "✓");
                                } else {
                                  tmp$2 = null;
                                }
                                var match$6 = Curry._1(form[/* results */2], /* MinChoices */7);
                                var tmp$3;
                                if (match$6) {
                                  var match$7 = match$6[0];
                                  tmp$3 = match$7 ? React.createElement("div", {
                                          className: "failure"
                                        }, match$7[0]) : React.createElement("div", {
                                          className: "success"
                                        }, "✓");
                                } else {
                                  tmp$3 = null;
                                }
                                return React.createElement("form", {
                                            className: "form",
                                            onSubmit: (function (param) {
                                                return partial_arg$1(partial_arg, param);
                                              })
                                          }, React.createElement("h1", undefined, "New Poll"), React.createElement("div", {
                                                className: "form-row"
                                              }, React.createElement("label", {
                                                    className: "label-lg",
                                                    htmlFor: "signup--title"
                                                  }, "Poll ID"), React.createElement("input", {
                                                    id: "signup--title",
                                                    disabled: form[/* submitting */3],
                                                    type: "text",
                                                    value: form[/* state */0][/* pollId */0],
                                                    onBlur: (function ($$event) {
                                                        return Curry._2(form[/* blur */5], /* PollId */0, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnBlur */3]($$event)]));
                                                      }),
                                                    onChange: (function ($$event) {
                                                        return Curry._2(form[/* change */4], /* PollId */0, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnChange */2]($$event)]));
                                                      })
                                                  }), tmp), React.createElement("div", {
                                                className: "form-row"
                                              }, React.createElement("label", {
                                                    className: "label-lg",
                                                    htmlFor: "signup--title"
                                                  }, "Title"), React.createElement("input", {
                                                    id: "signup--title",
                                                    disabled: form[/* submitting */3],
                                                    type: "text",
                                                    value: form[/* state */0][/* title */1],
                                                    onBlur: (function ($$event) {
                                                        return Curry._2(form[/* blur */5], /* Title */1, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnBlur */3]($$event)]));
                                                      }),
                                                    onChange: (function ($$event) {
                                                        return Curry._2(form[/* change */4], /* Title */1, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnChange */2]($$event)]));
                                                      })
                                                  }), tmp$1), React.createElement("div", {
                                                className: "form-row"
                                              }, React.createElement("label", {
                                                    className: "label-lg",
                                                    htmlFor: "signup--title"
                                                  }, "Description"), React.createElement("input", {
                                                    id: "signup--title",
                                                    disabled: form[/* submitting */3],
                                                    type: "text",
                                                    value: form[/* state */0][/* description */2],
                                                    onBlur: (function ($$event) {
                                                        return Curry._2(form[/* blur */5], /* Description */2, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnBlur */3]($$event)]));
                                                      }),
                                                    onChange: (function ($$event) {
                                                        return Curry._2(form[/* change */4], /* Description */2, /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnChange */2]($$event)]));
                                                      })
                                                  }), tmp$2), React.createElement("div", {
                                                className: "form-row"
                                              }, React.createElement("label", {
                                                    className: "label-lg",
                                                    htmlFor: "signup--title"
                                                  }, "Min choices"), React.createElement("input", {
                                                    id: "signup--title",
                                                    disabled: form[/* submitting */3],
                                                    type: "text",
                                                    value: String(form[/* state */0][/* minChoices */6]),
                                                    onBlur: (function ($$event) {
                                                        return Curry._2(form[/* blur */5], /* MinChoices */7, /* Int */Block.__(1, [Caml_format.caml_int_of_string(Formality__PublicHelpers.Dom[/* toValueOnBlur */3]($$event))]));
                                                      }),
                                                    onChange: (function ($$event) {
                                                        return Curry._2(form[/* change */4], /* MinChoices */7, /* Int */Block.__(1, [Caml_format.caml_int_of_string(Formality__PublicHelpers.Dom[/* toValueOnChange */2]($$event))]));
                                                      })
                                                  }), tmp$3), React.createElement("ol", undefined, $$Array.mapi((function (i, value) {
                                                      var match = i >= 2;
                                                      var match$1 = Curry._1(form[/* results */2], /* Option */Block.__(0, [i]));
                                                      var tmp;
                                                      if (match$1) {
                                                        var match$2 = match$1[0];
                                                        tmp = match$2 ? React.createElement("div", {
                                                                className: "failure"
                                                              }, match$2[0]) : React.createElement("div", {
                                                                className: "success"
                                                              }, "✓");
                                                      } else {
                                                        tmp = null;
                                                      }
                                                      return React.createElement("li", {
                                                                  key: String(i)
                                                                }, React.createElement("input", {
                                                                      value: value,
                                                                      onChange: (function ($$event) {
                                                                          return Curry._2(form[/* change */4], /* Option */Block.__(0, [i]), /* String */Block.__(0, [Formality__PublicHelpers.Dom[/* toValueOnChange */2]($$event)]));
                                                                        })
                                                                    }), match ? React.createElement("a", {
                                                                        onClick: (function () {
                                                                            return Curry._2(form[/* change */4], /* DelOption */Block.__(1, [i]), /* NoValue */0);
                                                                          })
                                                                      }, "[-]") : "", tmp);
                                                    }), form[/* state */0][/* options */3])), React.createElement("a", {
                                                onClick: (function () {
                                                    return Curry._2(form[/* change */4], /* AddOption */3, /* NoValue */0);
                                                  })
                                              }, "Add option"), React.createElement("button", {
                                                type: "reset"
                                              }, "Reset"), React.createElement("button", {
                                                type: "submit"
                                              }, "Create Poll"));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.Form = Form;
exports.Container = Container;
exports.component = component;
exports.make = make;
/* Validators Not a pure module */
