// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PostData$ReactTemplate = require("../Data/PostData.js");
var ProfileData$ReactTemplate = require("../Data/ProfileData.js");

function renderPost(post) {
  return React.createElement("div", {
              key: String(post[/* id */0])
            }, post[/* text */1]);
}

function reducer(action, state) {
  if (action.tag) {
    return /* Update */Block.__(0, [/* record */[
                /* eos */state[/* eos */0],
                /* accountName */state[/* accountName */1],
                /* postData */action[0],
                /* profileData */state[/* profileData */3]
              ]]);
  } else {
    return /* Update */Block.__(0, [/* record */[
                /* eos */state[/* eos */0],
                /* accountName */state[/* accountName */1],
                /* postData */state[/* postData */2],
                /* profileData */action[0]
              ]]);
  }
}

var component = ReasonReact.reducerComponent("ProfilePage");

function make(eos, accountName, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Curry._1(self[/* send */3], /* ChangePostData */Block.__(1, [/* Loading */1]));
              ProfileData$ReactTemplate.fetch(eos, accountName).then((function (profileData) {
                      console.log("profileData", profileData);
                      Curry._1(self[/* send */3], /* ChangeProfileData */Block.__(0, [profileData]));
                      if (typeof profileData === "number" || profileData.tag) {
                        return Promise.resolve(/* () */0);
                      } else {
                        var profile = profileData[0];
                        PostData$ReactTemplate.fetch(eos, accountName, Math.max(0, profile[/* numPosts */6] - 2 | 0), profile[/* numPosts */6], /* Some */[2]).then((function (postData) {
                                Curry._1(self[/* send */3], /* ChangePostData */Block.__(1, [postData]));
                                return Promise.resolve(/* () */0);
                              }));
                        return Promise.resolve(/* () */0);
                      }
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* postData */2];
              var tmp;
              tmp = typeof match === "number" ? "Loading..." : (
                  match.tag ? "Failed to load" : React.createElement("div", undefined, $$Array.map(renderPost, match[0]), React.createElement("p", undefined, "Has more? " + (String(match[1]) + " ")))
                );
              return React.createElement("div", undefined, React.createElement("h1", undefined, accountName), "Profile", React.createElement("div", undefined, tmp));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* eos */eos,
                      /* accountName */accountName,
                      /* postData : NotAsked */0,
                      /* profileData : NotAsked */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var numPerPage = 2;

exports.renderPost = renderPost;
exports.reducer = reducer;
exports.component = component;
exports.numPerPage = numPerPage;
exports.make = make;
/* component Not a pure module */
