// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Scatter$ReactTemplate = require("./External/Scatter.js");

var localNetwork = Scatter$ReactTemplate.Network[/* make */0](/* http */-988374136, /* eos */5047497, "127.0.0.1", 8888);

var httpEndpoint = "http://127.0.01:8888";

var eosConfig = {
  httpEndpoint: httpEndpoint
};

var codeName = "eosstrawpoll";

var network = localNetwork;

exports.codeName = codeName;
exports.localNetwork = localNetwork;
exports.network = network;
exports.httpEndpoint = httpEndpoint;
exports.eosConfig = eosConfig;
/* localNetwork Not a pure module */
