// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function fromUrl(url) {
  var match = url[/* path */0];
  if (match) {
    var accountName = match[0];
    var exit = 0;
    if (accountName === "about" && !match[1]) {
      return /* About */1;
    } else {
      exit = 1;
    }
    if (exit === 1) {
      var match$1 = match[1];
      if (match$1) {
        var match$2 = match$1[1];
        var pollId = match$1[0];
        if (match$2) {
          if (match$2[0] === "results" && !match$2[1]) {
            return /* PollResults */Block.__(2, [
                      accountName,
                      pollId
                    ]);
          } else {
            return /* Home */0;
          }
        } else {
          return /* Poll */Block.__(1, [
                    accountName,
                    pollId
                  ]);
        }
      } else {
        return /* Profile */Block.__(0, [accountName]);
      }
    }
    
  } else {
    return /* Home */0;
  }
}

function toString(route) {
  if (typeof route === "number") {
    if (route === 0) {
      return "/";
    } else {
      return "/about";
    }
  } else {
    switch (route.tag | 0) {
      case 0 : 
          return "/" + route[0];
      case 1 : 
          return "/" + (route[0] + ("/" + route[1]));
      case 2 : 
          return "/" + (route[0] + ("/" + (route[1] + "/results")));
      
    }
  }
}

exports.fromUrl = fromUrl;
exports.toString = toString;
/* No side effect */
