// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Eosjs = require("eosjs");
var Env$ReactTemplate = require("./Env.js");
var Scatter$ReactTemplate = require("./External/Scatter.js");

var defaultEosConfig = {
  httpEndpoint: Env$ReactTemplate.httpEndpoint,
  verbose: false
};

function loadEosReadOnly() {
  return Eosjs(defaultEosConfig);
}

function loadScatterEos(scatter) {
  return Scatter$ReactTemplate.eos(scatter, Env$ReactTemplate.network, (function (prim) {
                return Eosjs(prim);
              }), defaultEosConfig, "http");
}

exports.defaultEosConfig = defaultEosConfig;
exports.loadEosReadOnly = loadEosReadOnly;
exports.loadScatterEos = loadScatterEos;
/* eosjs Not a pure module */
