version: "3"

services:

  nodeosd:
    build:
      context: .
    image: tgfpio/eos
    command: /start_nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./build.sh:/build.sh:ro
      - ./start_nodeosd.sh:/start_nodeosd.sh:ro
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini:ro
      - ../contracts:/src:ro
      - ../../dist/contracts:/dist

  keosd:
    image: tgfpio/eos
    command: /opt/eosio/bin/keosd
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./build.sh:/build.sh:ro
      - ../contracts:/src:ro
      - ../../dist/contracts:/dist

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
