// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");

var main = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.flexDirection(TypedGlamor.rowReverse),
        /* [] */0
      ]
    ]);

var form = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.flex_(TypedGlamor.auto),
      /* [] */0
    ]);

var sidebar = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.flexShrink(0),
      /* :: */[
        TypedGlamor.width(TypedGlamor.px(250)),
        /* [] */0
      ]
    ]);

var poll = TypedGlamor.css(/* None */0, /* [] */0);

var pollTitle = TypedGlamor.css(/* None */0, /* [] */0);

var optionList = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* :: */[
        TypedGlamor.flexDirection(TypedGlamor.column),
        /* [] */0
      ]
    ]);

var option = TypedGlamor.css(/* None */0, /* [] */0);

var optionInput = TypedGlamor.css(/* None */0, /* [] */0);

exports.main = main;
exports.form = form;
exports.sidebar = sidebar;
exports.poll = poll;
exports.pollTitle = pollTitle;
exports.optionList = optionList;
exports.option = option;
exports.optionInput = optionInput;
/* main Not a pure module */
