// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");
var AppStyles$ReactTemplate = require("./AppStyles.js");

var _global = TypedGlamor.$$global(".ais-InstantSearch__root", /* :: */[
      TypedGlamor.display(TypedGlamor.flex),
      /* [] */0
    ]);

var filters = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.width(AppStyles$ReactTemplate.sidebarWidth),
      /* [] */0
    ]);

var main = TypedGlamor.css(/* None */0, /* [] */0);

exports._global = _global;
exports.filters = filters;
exports.main = main;
/* _global Not a pure module */
