version: "3"

services:

  mongo-master:
    image: mongo
    hostname: mongo-master
    restart: always
    command: --smallfiles --replSet rs
    ports:
      - 27017:27017

  mongo-slave1:
    image: mongo
    hostname: mongo-slave1
    restart: always
    command: --smallfiles --replSet rs
    ports:
      - 27018:27017

  mongo-slave2:
    image: mongo
    hostname: mongo-slave2
    restart: always
    command: --smallfiles --replSet rs
    ports:
      - 27019:27017

  mongo-setup:
    image: mongo
    volumes:
      - ./start_mongo.sh:/start_mongo.sh
    entrypoint: [ "bash", "/start_mongo.sh" ]

  nodeosd:
    build:
      context: .
    image: eosio/eos
    links:
      - mongo-master
      - mongo-slave1
      - mongo-slave2
      - mongo-setup
    depends_on:
      - mongo-master
      - mongo-slave1
      - mongo-slave2
      - mongo-setup
    command: /start_nodeosd.sh
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/mnt/dev/data
      - ./build.sh:/build.sh:ro
      - ./start_nodeosd.sh:/start_nodeosd.sh:ro
      - ./config.ini:/mnt/dev/config/config.ini:ro
      - ../contracts:/src:ro
      - ../build/contracts:/dist

  keosd:
    image: eosio/eos
    command: keosd --unlock-timeout 999999
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/mnt/dev/data
      - ./build.sh:/build.sh:ro
      - ../contracts:/src:ro
      - ../build/contracts:/dist

  website:
    image: node
    command: /start_api.sh
    links:
      - nodeosd
    volumes:
      - ./start_api.sh:/start_api.sh:ro
      - ../build/website:/dist:ro
    ports:
      - 3001:3001
    env_file:
      - ../.env.dev

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
