version: "3"

services:

  nodeosd:
    build:
      context: .
    image: tgfpio/eos
    command: /opt/eosio/bin/nodeosd.sh -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini

  keosd:
    image: tgfpio/eos
    command: /opt/eosio/bin/keosd
    hostname: keosd
    links:
      - nodeosd
    volumes:
      # - ./start_keosd.sh:/start_keosd.sh
      # - ../contracts:/src/contracts
      # - ../unittests:/src/unittests
      - ../contracts/CMakeLists.txt:/eos/contracts/CMakeLists.txt
      - ../unittests/CMakeLists.txt:/eos/unittests/CMakeLists.txt
      - ../contracts/tgfpio.token:/eos/contracts/tgfpio.token
      - ../contracts/tgfpio.token:/opt/eosio/contracts/tgfpio.token
      - ../unittests/tgfpio.token_tests.cpp:/eos/unittests/tgfpio.token_tests.cpp
      - ../contracts/eosio.nft:/eos/contracts/eosio.nft
      - ../contracts/eosio.nft:/opt/eosio/contracts/eosio.nft
      - ../unittests/eosio.nft_tests.cpp:/eos/unittests/eosio.nft_tests.cpp
      - keosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
