version: "3"

services:

  nodeosd:
    build:
      context: .
    image: tgfpio/eos
    command: /start_nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./build.sh:/build.sh:ro
      - ./start_nodeosd.sh:/start_nodeosd.sh:ro
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini:ro
      - ../contracts:/src:ro
      - ../dist/contracts:/dist
      # - ../include:/opt/eosio/include

  keosd:
    image: tgfpio/eos
    command: /opt/eosio/bin/keosd
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./build.sh:/build.sh:ro
      - ../contracts:/src:ro
      - ../dist/contracts:/dist
      # - ../contracts:/src/contracts
      # - ../unittests:/src/unittests
      # - ../contracts/CMakeLists.txt:/eos/contracts/CMakeLists.txt
      # - ../unittests/CMakeLists.txt:/eos/unittests/CMakeLists.txt
      # - ../contracts/tgfpio.token:/eos/contracts/tgfpio.token
      # - ../unittests/tgfpio.token_tests.cpp:/eos/unittests/tgfpio.token_tests.cpp
      # - ../contracts/tgfpio.body:/eos/contracts/tgfpio.body
      # - ../unittests/tgfpio.body_tests.cpp:/eos/unittests/tgfpio.body_tests.cpp
      # - ../contracts/eosio.nft:/eos/contracts/eosio.nft
      # - ../unittests/eosio.nft_tests.cpp:/eos/unittests/eosio.nft_tests.cpp
      # - ../include:/opt/eosio/include

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
