// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var initial = /* record */[
  /* scatter : None */0,
  /* identity : None */0,
  /* language : English */0
];

exports.initial = initial;
/* No side effect */
