// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Eos$ReactTemplate = require("./External/Eos.js");

function decode(j) {
  var partial_arg = Eos$ReactTemplate.AccountName[/* decode */0];
  var partial_arg$1 = Eos$ReactTemplate.AccountName[/* decode */0];
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j),
          /* title */Json_decode.field("title", Json_decode.string, j),
          /* description */Json_decode.field("description", Json_decode.string, j),
          /* options */Json_decode.field("options", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), j),
          /* whitelist */Json_decode.field("whitelist", (function (param) {
                  return Json_decode.array(partial_arg, param);
                }), j),
          /* blacklist */Json_decode.field("blacklist", (function (param) {
                  return Json_decode.array(partial_arg$1, param);
                }), j),
          /* minChoices */Json_decode.field("min_choices", Json_decode.$$int, j),
          /* maxChoices */Json_decode.field("max_choices", Json_decode.$$int, j),
          /* openTime */Json_decode.field("open_time", Json_decode.$$int, j),
          /* closeTime */Json_decode.field("close_time", Json_decode.$$int, j)
        ];
}

var Create = /* module */[/* decode */decode];

function decode$1(j) {
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j)
        ];
}

var Close = /* module */[/* decode */decode$1];

function decode$2(j) {
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j)
        ];
}

var Destroy = /* module */[/* decode */decode$2];

function decode$3(j) {
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j),
          /* voter */Json_decode.field("voter", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* choices */Json_decode.field("choices", (function (param) {
                  return Json_decode.array(Json_decode.$$int, param);
                }), j)
        ];
}

var Vote = /* module */[/* decode */decode$3];

function decode$4(j) {
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j),
          /* commenter */Json_decode.field("voter", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* content */Json_decode.field("choices", Json_decode.string, j)
        ];
}

var Comment = /* module */[/* decode */decode$4];

function decode$5(j) {
  return /* record */[
          /* pollCreator */Json_decode.field("poll_creator", Eos$ReactTemplate.AccountName[/* decode */0], j),
          /* pollId */Json_decode.field("poll_id", Json_decode.string, j),
          /* newDescription */Json_decode.field("choices", Json_decode.string, j)
        ];
}

var Update = /* module */[/* decode */decode$5];

var Action = /* module */[];

exports.Create = Create;
exports.Close = Close;
exports.Destroy = Destroy;
exports.Vote = Vote;
exports.Comment = Comment;
exports.Update = Update;
exports.Action = Action;
/* No side effect */
