// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Mongodb = require("mongodb");
var WebServerEnv$ReactTemplate = require("./Env/WebServerEnv.js");

function onCreate(client, _) {
  client.db(WebServerEnv$ReactTemplate.mongoAppDb).collection("polls");
  return /* () */0;
}

function listen() {
  return Mongodb.MongoClient.connect(WebServerEnv$ReactTemplate.mongoUri).then((function (client) {
                console.log("Connected to MongoDB");
                return Promise.resolve(client.db(WebServerEnv$ReactTemplate.mongoEosDb).collection("actions").watch(/* array */[{
                                    $match: Js_dict.fromList(/* :: */[
                                          /* tuple */[
                                            "fullDocument.account",
                                            WebServerEnv$ReactTemplate.contractAccount
                                          ],
                                          /* [] */0
                                        ])
                                  }]).on("change", (function (change) {
                                  console.log("CHANGED:", change);
                                  return /* () */0;
                                })));
              }));
}

exports.onCreate = onCreate;
exports.listen = listen;
/* Js_dict Not a pure module */
