// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Scatter$ReactTemplate = require("./Scatter.js");

var localNetwork = Scatter$ReactTemplate.Network[/* make */0](/* http */-988374136, /* eos */5047497, "127.0.0.1", 8888);

var codeName = "twitteos";

var network = localNetwork;

exports.codeName = codeName;
exports.localNetwork = localNetwork;
exports.network = network;
/* localNetwork Not a pure module */
