// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function encode(prim) {
  return prim;
}

var AccountName = /* module */[
  /* decode */Json_decode.string,
  /* encode */encode
];

function encode$1(prim) {
  return prim;
}

var Asset = /* module */[
  /* decode */Json_decode.string,
  /* encode */encode$1
];

function encode$2(prim) {
  return prim;
}

var TrxId = /* module */[
  /* decode */Json_decode.string,
  /* encode */encode$2
];

var Config = /* module */[];

var Account = /* module */[];

var Action = /* module */[];

exports.AccountName = AccountName;
exports.Asset = Asset;
exports.TrxId = TrxId;
exports.Config = Config;
exports.Account = Account;
exports.Action = Action;
/* No side effect */
