// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Eosjs = require("eosjs");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Env$ReactTemplate = require("./Env.js");
var Scatter$ReactTemplate = require("./Libraries/Scatter.js");

function make(scatter) {
  var eos = Scatter$ReactTemplate.eos(scatter, Env$ReactTemplate.scatterNetwork, (function (prim) {
          return Eosjs(prim);
        }), Env$ReactTemplate.eosConfig, "http");
  return eos.contract(process.env.CONTRACT_ACCOUNT);
}

var Contract = /* module */[/* make */make];

function create(contract, pollCreator, pollId, title, $staropt$star, options, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, $staropt$star$5, $staropt$star$6, _) {
  var description = $staropt$star ? $staropt$star[0] : "";
  var whitelist = $staropt$star$1 ? $staropt$star$1[0] : /* array */[];
  var blacklist = $staropt$star$2 ? $staropt$star$2[0] : /* array */[];
  var minChoices = $staropt$star$3 ? $staropt$star$3[0] : 0;
  var maxChoices = $staropt$star$4 ? $staropt$star$4[0] : 0;
  var openTime = $staropt$star$5 ? $staropt$star$5[0] : 0;
  var closeTime = $staropt$star$6 ? $staropt$star$6[0] : 0;
  return contract.create({
              poll_creator: pollCreator,
              poll_id: pollId,
              title: title,
              description: description,
              options: options,
              whitelist: whitelist,
              blacklist: blacklist,
              min_choices: minChoices,
              max_choices: maxChoices,
              open_time: openTime,
              close_time: closeTime,
              app_label: process.env.APP_LABEL
            }, {
              authorization: /* array */["" + (String(pollCreator) + "@active")]
            });
}

function close(contract, pollCreator, pollId) {
  return contract.close({
              poll_creator: pollCreator,
              poll_id: pollId,
              app_label: process.env.APP_LABEL
            }, {
              authorization: /* array */["" + (String(pollCreator) + "@active")]
            });
}

function vote(contract, pollCreator, pollId, voter, choices) {
  return contract.vote({
              poll_creator: pollCreator,
              poll_id: pollId,
              voter: voter,
              choices: choices,
              app_label: process.env.APP_LABEL
            }, {
              authorization: /* array */["" + (String(voter) + "@active")]
            });
}

function decode(json) {
  return /* record */[
          /* voter */Json_decode.field("voter", Json_decode.string, json),
          /* time */Json_decode.field("time", Json_decode.$$int, json),
          /* holdings */Json_decode.field("holdings", Json_decode.string, json),
          /* choices */Json_decode.field("choices", (function (param) {
                  return Json_decode.array(Json_decode.$$int, param);
                }), json)
        ];
}

var Vote = /* module */[/* decode */decode];

function decode$1(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* creator */Json_decode.field("poll_creator", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* options */Json_decode.field("options", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* votes */Json_decode.field("votes", (function (param) {
                  return Json_decode.array(decode, param);
                }), json),
          /* minNumChoices */Json_decode.field("min_num_choices", Json_decode.$$int, json),
          /* maxNumChoices */Json_decode.field("max_num_choices", Json_decode.$$int, json),
          /* whitelist */Json_decode.field("whitelist", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* blacklist */Json_decode.field("blacklist", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* createTime */Json_decode.field("create_time", Json_decode.$$int, json),
          /* openTime */Json_decode.field("open_time", Json_decode.$$int, json),
          /* closeTime */Json_decode.field("close_time", Json_decode.$$int, json)
        ];
}

var Poll = /* module */[/* decode */decode$1];

exports.Contract = Contract;
exports.create = create;
exports.close = close;
exports.vote = vote;
exports.Vote = Vote;
exports.Poll = Poll;
/* eosjs Not a pure module */
