// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var empty = {
  id: "",
  pollId: "",
  pollCreator: "",
  title: "",
  description: "",
  options: /* array */[],
  whitelist: /* array */[],
  blacklist: /* array */[],
  minChoices: 0,
  maxChoices: 0,
  openTime: 0,
  closeTime: 0,
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  appLabel: ""
};

var Poll = /* module */[/* empty */empty];

var empty$1 = {
  id: "",
  pollId: "",
  pollCreator: "",
  voter: "",
  choices: /* array */[],
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  appLabel: ""
};

var Vote = /* module */[/* empty */empty$1];

var empty$2 = {
  id: "",
  pollId: "",
  pollCreator: "",
  commenter: "",
  content: "",
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  appLabel: ""
};

var Comment = /* module */[/* empty */empty$2];

var empty$3 = {
  id: "",
  account: ""
};

var Settings = /* module */[/* empty */empty$3];

var empty$4 = {
  id: "",
  num: 0,
  time: ""
};

var Block = /* module */[/* empty */empty$4];

var empty$5 = {
  action_num: 0,
  trx_id: "",
  cfa: false,
  account: "",
  name: "",
  authorization: /* array */[],
  hex_data: "",
  data: null
};

function create(j) {
  return {
          poll_creator: Json_decode.field("poll_creator", Json_decode.string, j),
          poll_id: Json_decode.field("poll_id", Json_decode.string, j),
          title: Json_decode.field("title", Json_decode.string, j),
          description: Json_decode.field("description", Json_decode.string, j),
          options: Json_decode.field("options", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), j),
          whitelist: Json_decode.field("whitelist", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), j),
          blacklist: Json_decode.field("blacklist", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), j),
          min_choices: Json_decode.field("min_choices", Json_decode.$$int, j),
          max_choices: Json_decode.field("max_choices", Json_decode.$$int, j),
          open_time: Json_decode.field("open_time", Json_decode.$$int, j),
          close_time: Json_decode.field("close_time", Json_decode.$$int, j),
          app_label: Json_decode.field("app_label", Json_decode.string, j)
        };
}

function vote(j) {
  return {
          poll_creator: Json_decode.field("poll_creator", Json_decode.string, j),
          poll_id: Json_decode.field("poll_id", Json_decode.string, j),
          voter: Json_decode.field("voter", Json_decode.string, j),
          choices: Json_decode.field("choices", (function (param) {
                  return Json_decode.array(Json_decode.$$int, param);
                }), j),
          app_label: Json_decode.field("app_label", Json_decode.string, j)
        };
}

var Decode = /* module */[
  /* DecodeError */Json_decode.DecodeError,
  /* bool */Json_decode.bool,
  /* float */Json_decode.$$float,
  /* int */Json_decode.$$int,
  /* string */Json_decode.string,
  /* char */Json_decode.$$char,
  /* date */Json_decode.date,
  /* nullable */Json_decode.nullable,
  /* nullAs */Json_decode.nullAs,
  /* array */Json_decode.array,
  /* list */Json_decode.list,
  /* pair */Json_decode.pair,
  /* tuple2 */Json_decode.tuple2,
  /* tuple3 */Json_decode.tuple3,
  /* tuple4 */Json_decode.tuple4,
  /* dict */Json_decode.dict,
  /* field */Json_decode.field,
  /* at */Json_decode.at,
  /* optional */Json_decode.optional,
  /* oneOf */Json_decode.oneOf,
  /* either */Json_decode.either,
  /* withDefault */Json_decode.withDefault,
  /* map */Json_decode.map,
  /* andThen */Json_decode.andThen,
  /* create */create,
  /* vote */vote
];

var EosAction = /* module */[
  /* empty */empty$5,
  /* Decode */Decode
];

var empty$6 = {
  block_num: 0,
  block_id: "",
  irreversible: false,
  block: {
    timestamp: "",
    producer: "",
    confirmed: 0,
    previous: "",
    transaction_mroot: "",
    action_mroot: "",
    schedule_version: 0,
    producer_signature: ""
  }
};

var EosBlock = /* module */[/* empty */empty$6];

exports.Poll = Poll;
exports.Vote = Vote;
exports.Comment = Comment;
exports.Settings = Settings;
exports.Block = Block;
exports.EosAction = EosAction;
exports.EosBlock = EosBlock;
/* No side effect */
