// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var empty = {
  id: "",
  pollId: "",
  pollCreator: "",
  title: "",
  description: "",
  options: /* array */[],
  whitelist: /* array */[],
  blacklist: /* array */[],
  minChoices: 0,
  maxChoices: 0,
  openTime: 0,
  closeTime: 0,
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  metadata: ""
};

var Poll = /* module */[/* empty */empty];

var empty$1 = {
  id: "",
  pollRef: "",
  pollId: "",
  pollCreator: "",
  voter: "",
  choices: /* array */[],
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  metadata: ""
};

var Vote = /* module */[/* empty */empty$1];

var empty$2 = {
  id: "",
  pollId: "",
  pollCreator: "",
  commenter: "",
  content: "",
  blockId: "",
  blockNum: 0,
  blockTime: "",
  trxId: "",
  metadata: ""
};

var Comment = /* module */[/* empty */empty$2];

var empty$3 = {
  id: "",
  account: ""
};

var Settings = /* module */[/* empty */empty$3];

var empty$4 = {
  id: "",
  num: 0,
  time: "",
  numPolls: 0,
  numCloses: 0,
  numVotes: 0,
  numComments: 0,
  numReactions: 0,
  numDonations: 0
};

var Block$1 = /* module */[/* empty */empty$4];

var empty$5 = {
  action_num: 0,
  trx_id: "",
  cfa: false,
  account: "",
  name: "",
  authorization: /* array */[],
  hex_data: "",
  data: null
};

function getData(action) {
  if (action.account === process.env.CONTRACT_ACCOUNT) {
    var match = action.name;
    var match$1 = action.data;
    switch (match) {
      case "close" : 
          if (match$1 == null) {
            return /* None */0;
          } else {
            return /* Some */[/* Close */Block.__(1, [match$1])];
          }
      case "comment" : 
          if (match$1 == null) {
            return /* None */0;
          } else {
            return /* Some */[/* Comment */Block.__(3, [match$1])];
          }
      case "create" : 
          if (match$1 == null) {
            return /* None */0;
          } else {
            return /* Some */[/* Create */Block.__(0, [match$1])];
          }
      case "vote" : 
          if (match$1 == null) {
            return /* None */0;
          } else {
            return /* Some */[/* Vote */Block.__(2, [match$1])];
          }
      default:
        return /* None */0;
    }
  } else {
    return /* None */0;
  }
}

var EosAction = /* module */[
  /* empty */empty$5,
  /* getData */getData
];

var empty$6 = {
  block_num: 0,
  block_id: "",
  irreversible: false,
  block: {
    timestamp: "",
    producer: "",
    confirmed: 0,
    previous: "",
    transaction_mroot: "",
    action_mroot: "",
    schedule_version: 0,
    producer_signature: "",
    transactions: /* array */[]
  }
};

var EosBlock = /* module */[/* empty */empty$6];

exports.Poll = Poll;
exports.Vote = Vote;
exports.Comment = Comment;
exports.Settings = Settings;
exports.Block = Block$1;
exports.EosAction = EosAction;
exports.EosBlock = EosBlock;
/* No side effect */
